# Cloudflare Tunnel Configuration Template
# Replace <TUNNEL_ID> with your actual tunnel ID
# See: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/

tunnel: <TUNNEL_ID>
credentials-file: /home/pi/.cloudflared/<TUNNEL_ID>.json

ingress:
  - hostname: yourblog.example.com
    service: http://localhost:3000
  - service: http_status:404
